### ISSUE TITLE
The print functions don't "flush"

### ISSUE THREAD

**Issue by louisabraham** [andrewray/iocamljs#10]
Try any print function (I tried print_int and Printf.printf) in https://andrewray.github.io/iocamljs/min.html or https://andrewray.github.io/iocamljs/full.html.

The output is not visible until you print the next "\n" character.
It is "as if" there is no flush.

**Comment by andrewray** [comment]
That is the expected behaviour, and comes from the underlying implementation js_of_ocaml provides for the file IO subsystem of ocaml.

I believe a `flush` call will still work, and, as you note, printing a newline also flushes.

**Comment by louisabraham** [comment]
Thanks.
Is it a bug of js_of_ocaml then?
Because print_int flushes in the toplevel.

**Comment by hhugo** [comment]
Just fixed the issue in https://github.com/ocsigen/js_of_ocaml/commit/52cf638ad1778b62bebaed34f9861bcaca8ffe05
