### ISSUE TITLE
iocamljs doesnt seem to evaluate anything any more

### ISSUE THREAD

**Issue by avsm** [andrewray/iocamljs#8]
I've packaged up the ocaml-dockerfile bindings with an iocamljs notebook to explain them here:
http://anil-code.recoil.org/ocaml-dockerfile/

This all worked great, but I've just packaged up a refresh of the package and failed to recreate it.  The iocamljs kernel now built (with latest opam-repository and OCaml 4.02.3) fails to evaluate the statements when play is pressed, but throws no errors in the JS console either. I'm a little stumped about where to start debugging and wondered if anyone else had this problem.

There's a Dockerfile that builds everything here:
https://github.com/avsm/ocaml-dockerfile/blob/master/Dockerfile.doc
If there's anything obviously wrong would love to know, otherwise will continue debugging.. (the Dockerfile can be run locally via `docker build -f Dockerfile.doc . dfile && docker run -p 8888:8888 -d dfile`

**Comment by andrewray** [comment]
Sounds familiar ... the last version of js_of_ocaml (that I tested...2.6 I think, I may be a version behind) requires `+dynlink.js` to build a top level.  See 32b38f99dc817667b54a0de361aed7d86575ddaa

**Comment by avsm** [comment]
Tried this in the latest Dockerfile but same error (previously there were warnings about dynlink symbols but they were ignored).  Am trying to downgade js_of_ocaml to see if that helps...

**Comment by andrewray** [comment]
I've added a wee line comment on the build script that seems to fix the problem here.

**Comment by avsm** [comment]
Thanks again for the help!

**Comment by andrewray** [comment]
No probs.  I was impressed seeing it work with cohttp_lwt inside docker.  The build stuff was ... confusingly clever ... but worked well.  Very interesting stuff.
