### ISSUE TITLE
Request: BER+implicits kernel

### ISSUE THREAD

**Issue by yallop** [andrewray/iocamljs#9]
It'd be very handy to have a kernel built from the [4.02.1+modular-implicits-ber compiler](https://github.com/ocaml/opam-repository/tree/master/compilers/4.02.1/4.02.1%2Bmodular-implicits-ber).

I managed to compile one ([`kernel.meta-modimp.js`](https://github.com/ocamllabs/iocamljs/blob/gh-pages/static/services/kernels/js/kernel.meta-modimp.js)) after pinning a few packages, following a procedure similar to https://github.com/andrewray/iocamljs/issues/7#issuecomment-76972955, but it doesn't actually work: it fails with various JavaScript errors, such as 

```
TypeError: IPython.Kernel is not a constructor
TypeError: this.kernel is null
```

and I'm not sure how best to debug it.

**Comment by andrewray** [comment]
```
$ opam install iocamljs-kernel js_of_ocaml.2.5 lwt.2.4.5
```

Then from this repository switch to the metaocaml branch and

```
$ make min
```

**Comment by yallop** [comment]
Thanks for the help!  The working kernel can be found here:
https://github.com/ocamllabs/iocamljs/blob/gh-pages/static/services/kernels/js/kernel.meta-modimp.js
